FROM python:3.7

RUN mkdir ~/.fonts

COPY FreeSans.ttf /.fonts

WORKDIR /app

COPY requirements.txt /app

RUN pip3 install -r requirements.txt --no-cache-dir

COPY . .
COPY ../data/ingredients.json .

CMD ["gunicorn", "foodgram.wsgi:application", "--bind", "0:8000" ]