# Generated by Django 4.0.4 on 2022-05-07 17:43

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, validators=[users.validators.validate_username], verbose_name='Логин'),
        ),
    ]
